### ISSUE TITLE
About Inference with .PNG images

### ISSUE THREAD

**Issue by nldhuyen0047** [OpenImagingLab/DualDn#7]
Hi, thanks for your excellent work.

I would like to test my images with your pretrained model by using inference file, but my images are not RAW, they are .PNG files.
Therefore, could you please explain to me that may I use the model with the .PNG files? If I would like to train the model, can I use the .PNG files?

Thank you so much.

**Comment by Lyricccco** [comment]
Thank you for your question and for taking the time to engage with our project !!

**Currently, DualDn is designed for and only accepts RAW files as input.** This is because denoising in dual domains requires feeding the network with original RAW data to effectively perform the dual-denoising process. Also, we have verified that DualDn is actually better than all state-of-the-art RAW or sRGB denoising methods in the paper and the project website. You can refer to a similar discussion in this [issue](https://github.com/OpenImagingLab/DualDn/issues/6) for more context.

However, we understand the interest in using formats like .PNG files. One potential approach to achieve both (i.e. accepting .PNG files as inputs and denoising in dual domains) is to unprocess the .PNG files into 'pseudo' RAW files. Techniques such as [UPI](https://arxiv.org/abs/1811.11127) and [CycleISP](https://arxiv.org/abs/2003.07761) could be utilized for this purpose. After unprocessing the .PNG files to 'pseudo' RAW files, DualDn can be applied as the denoising model, which may possibly works.

**Comment by nldhuyen0047** [comment]
Thank you for your reply and advice. I understand the problem and will look into it further.

I hope to see your work develop even further in the future.
